export const INSTALL_NPM = "npm install gradient-runtime";

export const INSTALL_SCRIPT = '<script src="gradient-runtime.global.js"></script>';

export const MOUNT_GLOBAL = [
  '<div id="hero" style="width:100%;height:100vh"></div>',
  "",
  '<script src="gradient-runtime.global.js"></script>',
  "<script>",
  "  const preset = {",
  '    presetVersion: 1,',
  '    engineId: "grain-v1",',
  "    params: {",
  "      uniform_seed: 42,",
  '      uniform_palette_colors_hex: [',
  '        "#0a0a12", "#1a1a2e", "#2563eb", "#f97316"',
  "      ],",
  "      uniform_motion_speed: 0.6,",
  "      uniform_flow_rotation_radians: 0.9,",
  "      uniform_flow_drift_speed_x: 0,",
  "      uniform_flow_drift_speed_y: 0,",
  "      uniform_warp_strength: 0.5,",
  "      uniform_warp_scale: 2.2,",
  "      uniform_turbulence: 0.4,",
  "      uniform_brightness: 1.05,",
  "      uniform_contrast: 1.12,",
  "      uniform_saturation: 1.2,",
  "      uniform_grain_amount: 0.12,",
  "      uniform_grain_size: 1.3,",
  "      uniform_reduce_motion_enabled: 0,",
  "    },",
  "  };",
  "",
  '  Gradient.mount("#hero", preset, { mode: "animated" });',
  "</script>",
].join("\n");

export const MOUNT_ESM = [
  'import { mountGradient } from "gradient-runtime";',
  "",
  "const preset = {",
  "  presetVersion: 1,",
  '  engineId: "grain-v1",',
  "  params: {",
  "    uniform_seed: 42,",
  '    uniform_palette_colors_hex: [',
  '      "#0a0a12", "#1a1a2e", "#2563eb", "#f97316"',
  "    ],",
  "    uniform_motion_speed: 0.6,",
  "    uniform_flow_rotation_radians: 0.9,",
  "    uniform_flow_drift_speed_x: 0,",
  "    uniform_flow_drift_speed_y: 0,",
  "    uniform_warp_strength: 0.5,",
  "    uniform_warp_scale: 2.2,",
  "    uniform_turbulence: 0.4,",
  "    uniform_brightness: 1.05,",
  "    uniform_contrast: 1.12,",
  "    uniform_saturation: 1.2,",
  "    uniform_grain_amount: 0.12,",
  "    uniform_grain_size: 1.3,",
  "    uniform_reduce_motion_enabled: 0,",
  "  },",
  "};",
  "",
  'const instance = mountGradient("#hero", preset, {',
  '  mode: "animated",',
  "});",
].join("\n");

export const MOUNT_REACT = [
  'import { GradientMount } from "gradient-runtime/react";',
  "",
  "const preset = { /* exported from generator */ };",
  "",
  "export function Hero() {",
  "  return (",
  "    <GradientMount",
  "      preset={preset}",
  '      options={{ mode: "animated" }}',
  '      className="w-full h-screen"',
  "    >",
  "      <h1>Hello</h1>",
  "    </GradientMount>",
  "  );",
  "}",
].join("\n");

export const SHARED_GLOBAL = [
  '<button class="cta-btn">Sign Up</button>',
  '<button class="cta-btn">Learn More</button>',
  '<button class="cta-btn">Contact</button>',
  "",
  '<script src="gradient-runtime.global.js"></script>',
  "<script>",
  '  const preset = "g2:WzY4LFs5ODU2MDgsNDM5...";',
  "",
  '  const shared = Gradient.mountShared(".cta-btn", preset, {',
  '    mode: "animated",',
  "  });",
  "",
  "  // After adding new elements to DOM:",
  "  shared.rescan();",
  "</script>",
].join("\n");

export const SHARED_ESM = [
  'import { mountSharedGradient } from "gradient-runtime";',
  "",
  'const preset = "g2:WzY4LFs5ODU2MDgsNDM5...";',
  "",
  'const shared = mountSharedGradient(".cta-btn", preset, {',
  '  mode: "animated",',
  "});",
  "",
  "// After adding new elements to DOM:",
  "shared.rescan();",
].join("\n");

export const SHARED_REACT = [
  'import { useEffect, useRef } from "react";',
  'import { mountSharedGradient } from "gradient-runtime/react";',
  "",
  "const preset = { /* exported from generator */ };",
  "",
  "export function SharedButtons() {",
  "  const ref = useRef<HTMLDivElement>(null);",
  "",
  "  useEffect(() => {",
  "    const el = ref.current;",
  "    if (!el) return;",
  "",
  "    const shared = mountSharedGradient(",
  '      el.querySelectorAll(".cta-btn"),',
  "      preset,",
  '      { mode: "animated" }',
  "    );",
  "",
  "    return () => shared.destroy();",
  "  }, []);",
  "",
  "  return (",
  "    <div ref={ref}>",
  '      <button className="cta-btn">Sign Up</button>',
  '      <button className="cta-btn">Learn More</button>',
  '      <button className="cta-btn">Contact</button>',
  "    </div>",
  "  );",
  "}",
].join("\n");

export const COMPACT_KEY_EXAMPLE = [
  "// Compact key exported from the generator",
  'const preset = "g2:WzY4LFs5ODU2MDgsNDM5NjAzOSwx...";',
  "",
  "// Works anywhere a preset object works",
  'Gradient.mount("#target", preset, { mode: "animated" });',
].join("\n");

export const PRESET_OBJECT_EXAMPLE = [
  "const preset = {",
  "  presetVersion: 1,",
  '  engineId: "grain-v1",',
  "  params: {",
  "    uniform_seed: 42,",
  '    uniform_palette_colors_hex: ["#0a0a12", "#1a1a2e", "#2563eb"],',
  "    uniform_motion_speed: 0.6,",
  "    uniform_flow_rotation_radians: 0.9,",
  "    uniform_flow_drift_speed_x: 0,",
  "    uniform_flow_drift_speed_y: 0,",
  "    uniform_warp_strength: 0.5,",
  "    uniform_warp_scale: 2.2,",
  "    uniform_turbulence: 0.4,",
  "    uniform_brightness: 1.05,",
  "    uniform_contrast: 1.12,",
  "    uniform_saturation: 1.2,",
  "    uniform_grain_amount: 0.12,",
  "    uniform_grain_size: 1.3,",
  "    uniform_reduce_motion_enabled: 0,",
  "  },",
  "};",
].join("\n");

export const HERO_HTML_EXAMPLE = [
  "<!DOCTYPE html>",
  '<html lang="en">',
  "<head>",
  '  <meta charset="UTF-8">',
  '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
  "  <title>Hero with Gradient</title>",
  "  <style>",
  "    * { margin: 0; padding: 0; box-sizing: border-box; }",
  "    body {",
  "      font-family: system-ui, sans-serif;",
  "      background: #0a0a0a;",
  "      color: #fff;",
  "    }",
  "    .hero {",
  "      position: relative;",
  "      width: 100%;",
  "      height: 100vh;",
  "      display: flex;",
  "      align-items: center;",
  "      justify-content: center;",
  "    }",
  "    .hero-content {",
  "      position: relative;",
  "      z-index: 10;",
  "      text-align: center;",
  "    }",
  "    h1 { font-size: 4rem; font-weight: 700; }",
  "    p  { margin-top: 1rem; font-size: 1.25rem; opacity: 0.7; }",
  "  </style>",
  "</head>",
  "<body>",
  '  <section class="hero" id="hero-bg">',
  '    <div class="hero-content">',
  "      <h1>Your Product</h1>",
  "      <p>Tagline goes here.</p>",
  "    </div>",
  "  </section>",
  "",
  '  <script src="gradient-runtime.global.js"></script>',
  "  <script>",
  '    Gradient.mount("#hero-bg", "g2:WzY4LFs5ODU2...", {',
  '      mode: "animated",',
  "    });",
  "  </script>",
  "</body>",
  "</html>",
].join("\n");

export const REACT_CHILDREN_EXAMPLE = [
  'import { GradientMount } from "gradient-runtime/react";',
  "",
  "const preset = { /* exported from generator */ };",
  "",
  "function GradientButton() {",
  "  return (",
  "    <GradientMount",
  "      preset={preset}",
  '      options={{ mode: "hover" }}',
  '      className="rounded-xl"',
  "    >",
  '      <button className="px-6 py-3 text-white font-medium">',
  "        Get started",
  "      </button>",
  "    </GradientMount>",
  "  );",
  "}",
].join("\n");

export const MODES_EXAMPLE = [
  'Gradient.mount("#bg", preset, { mode: "animated" });',
  'Gradient.mount("#card", preset, { mode: "static" });',
  'Gradient.mount("#btn", preset, { mode: "hover" });',
].join("\n");
