import type { Preset } from "@/types/preset";

const V = "1.0";

export const PRESETS: Preset[] = [
  {
    preset_version: V,
    preset_name: "Neon Drift",
    uniform_seed: 123.45,
    uniform_palette_colors_hex: ["#0a0a14", "#1e1b4b", "#6366f1", "#a78bfa", "#22d3ee"],
    uniform_motion_speed: 0.65,
    uniform_flow_rotation_radians: 1.0,
    uniform_warp_strength: 0.52,
    uniform_warp_scale: 2.2,
    uniform_turbulence: 0.38,
    uniform_brightness: 1.05,
    uniform_contrast: 1.12,
    uniform_saturation: 1.22,
    uniform_grain_amount: 0.14,
    uniform_grain_size: 1.3,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Sunset Ember",
    uniform_seed: 67.8,
    uniform_palette_colors_hex: ["#0f0a08", "#431407", "#ea580c", "#f59e0b", "#fef3c7"],
    uniform_motion_speed: 0.5,
    uniform_flow_rotation_radians: 0.5,
    uniform_warp_strength: 0.58,
    uniform_warp_scale: 2.0,
    uniform_turbulence: 0.42,
    uniform_brightness: 1.08,
    uniform_contrast: 1.18,
    uniform_saturation: 1.15,
    uniform_grain_amount: 0.1,
    uniform_grain_size: 1.2,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Arctic Flow",
    uniform_seed: 200.1,
    uniform_palette_colors_hex: ["#030712", "#0f172a", "#3b82f6", "#93c5fd", "#e0f2fe"],
    uniform_motion_speed: 0.45,
    uniform_flow_rotation_radians: 1.6,
    uniform_warp_strength: 0.48,
    uniform_warp_scale: 2.4,
    uniform_turbulence: 0.32,
    uniform_brightness: 1.02,
    uniform_contrast: 1.08,
    uniform_saturation: 1.05,
    uniform_grain_amount: 0.08,
    uniform_grain_size: 1.15,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Forest Deep",
    uniform_seed: 88.2,
    uniform_palette_colors_hex: ["#052e16", "#14532d", "#166534", "#4ade80", "#bbf7d0"],
    uniform_motion_speed: 0.35,
    uniform_flow_rotation_radians: 0.85,
    uniform_warp_strength: 0.55,
    uniform_warp_scale: 2.1,
    uniform_turbulence: 0.36,
    uniform_brightness: 0.98,
    uniform_contrast: 1.15,
    uniform_saturation: 1.08,
    uniform_grain_amount: 0.12,
    uniform_grain_size: 1.4,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Lavender Haze",
    uniform_seed: 155.0,
    uniform_palette_colors_hex: ["#1e1b4b", "#312e81", "#7c3aed", "#c4b5fd", "#ede9fe"],
    uniform_motion_speed: 0.55,
    uniform_flow_rotation_radians: 1.2,
    uniform_warp_strength: 0.5,
    uniform_warp_scale: 2.2,
    uniform_turbulence: 0.35,
    uniform_brightness: 1.0,
    uniform_contrast: 1.06,
    uniform_saturation: 1.18,
    uniform_grain_amount: 0.1,
    uniform_grain_size: 1.25,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Aurora",
    uniform_seed: 77.0,
    uniform_palette_colors_hex: ["#020617", "#0c4a6e", "#0ea5e9", "#f97316", "#fde047"],
    uniform_motion_speed: 0.5,
    uniform_flow_rotation_radians: 0.8,
    uniform_warp_strength: 0.55,
    uniform_warp_scale: 2.2,
    uniform_turbulence: 0.4,
    uniform_brightness: 1.06,
    uniform_contrast: 1.1,
    uniform_saturation: 1.2,
    uniform_grain_amount: 0.1,
    uniform_grain_size: 1.2,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Molten Core",
    uniform_seed: 42.0,
    uniform_palette_colors_hex: ["#1C0A00", "#6B2D0A", "#E85D04", "#FFBA08"],
    uniform_motion_speed: 1.0,
    uniform_flow_rotation_radians: 0.2,
    uniform_warp_strength: 0.9,
    uniform_warp_scale: 1.5,
    uniform_turbulence: 0.6,
    uniform_brightness: 1.15,
    uniform_contrast: 1.25,
    uniform_saturation: 1.3,
    uniform_grain_amount: 0.2,
    uniform_grain_size: 1.6,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Midnight Bloom",
    uniform_seed: 301.5,
    uniform_palette_colors_hex: ["#0F0A1F", "#2D1B4E", "#7B2CBF", "#C77DFF"],
    uniform_motion_speed: 0.45,
    uniform_flow_rotation_radians: 1.8,
    uniform_warp_strength: 0.35,
    uniform_warp_scale: 2.8,
    uniform_turbulence: 0.2,
    uniform_brightness: 1.02,
    uniform_contrast: 1.12,
    uniform_saturation: 1.18,
    uniform_grain_amount: 0.14,
    uniform_grain_size: 1.2,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Ocean Depths",
    uniform_seed: 77.3,
    uniform_palette_colors_hex: ["#03071e", "#0D1B2A", "#1B263B", "#415A77", "#778DA9", "#E0E1DD"],
    uniform_motion_speed: 0.35,
    uniform_flow_rotation_radians: 2.2,
    uniform_warp_strength: 0.45,
    uniform_warp_scale: 2.5,
    uniform_turbulence: 0.28,
    uniform_brightness: 0.98,
    uniform_contrast: 1.18,
    uniform_saturation: 0.95,
    uniform_grain_amount: 0.09,
    uniform_grain_size: 1.1,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Electric Mint",
    uniform_seed: 99.9,
    uniform_palette_colors_hex: ["#001011", "#0A4D4D", "#088F8F", "#00FFD1", "#7DF9FF"],
    uniform_motion_speed: 0.9,
    uniform_flow_rotation_radians: 0.6,
    uniform_warp_strength: 0.65,
    uniform_warp_scale: 2.0,
    uniform_turbulence: 0.45,
    uniform_brightness: 1.08,
    uniform_contrast: 1.2,
    uniform_saturation: 1.22,
    uniform_grain_amount: 0.16,
    uniform_grain_size: 1.35,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Rose Gold",
    uniform_seed: 12.7,
    uniform_palette_colors_hex: ["#1C0F0F", "#4A2C2A", "#B76E79", "#E8B4B8", "#FFE4E1"],
    uniform_motion_speed: 0.4,
    uniform_flow_rotation_radians: 1.0,
    uniform_warp_strength: 0.5,
    uniform_warp_scale: 2.2,
    uniform_turbulence: 0.32,
    uniform_brightness: 1.05,
    uniform_contrast: 1.1,
    uniform_saturation: 1.15,
    uniform_grain_amount: 0.11,
    uniform_grain_size: 1.25,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Void",
    uniform_seed: 0.1,
    uniform_palette_colors_hex: ["#000000", "#0a0a0a", "#1a1a1a", "#2d2d2d"],
    uniform_motion_speed: 0.2,
    uniform_flow_rotation_radians: 3.14,
    uniform_warp_strength: 0.3,
    uniform_warp_scale: 4.0,
    uniform_turbulence: 0.15,
    uniform_brightness: 0.9,
    uniform_contrast: 1.3,
    uniform_saturation: 0.9,
    uniform_grain_amount: 0.25,
    uniform_grain_size: 1.8,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Peach Fuzz",
    uniform_seed: 188.4,
    uniform_palette_colors_hex: ["#2D1810", "#6B4423", "#C4956A", "#E8C4A0", "#FFE5D9"],
    uniform_motion_speed: 0.5,
    uniform_flow_rotation_radians: 0.9,
    uniform_warp_strength: 0.55,
    uniform_warp_scale: 2.1,
    uniform_turbulence: 0.38,
    uniform_brightness: 1.1,
    uniform_contrast: 1.08,
    uniform_saturation: 1.12,
    uniform_grain_amount: 0.1,
    uniform_grain_size: 1.2,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Cyber Grid",
    uniform_seed: 255.0,
    uniform_palette_colors_hex: ["#0D0221", "#0F084B", "#26408B", "#00F5D4", "#7BFDEA"],
    uniform_motion_speed: 1.2,
    uniform_flow_rotation_radians: 0.3,
    uniform_warp_strength: 0.75,
    uniform_warp_scale: 1.6,
    uniform_turbulence: 0.55,
    uniform_brightness: 1.12,
    uniform_contrast: 1.22,
    uniform_saturation: 1.28,
    uniform_grain_amount: 0.22,
    uniform_grain_size: 1.5,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Dusty Sage",
    uniform_seed: 33.6,
    uniform_palette_colors_hex: ["#1A1F1A", "#3D4A3D", "#6B7B6B", "#9CAF9C", "#C5D4C5"],
    uniform_motion_speed: 0.25,
    uniform_flow_rotation_radians: 1.4,
    uniform_warp_strength: 0.4,
    uniform_warp_scale: 2.6,
    uniform_turbulence: 0.22,
    uniform_brightness: 0.97,
    uniform_contrast: 1.15,
    uniform_saturation: 1.05,
    uniform_grain_amount: 0.18,
    uniform_grain_size: 1.4,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
  {
    preset_version: V,
    preset_name: "Blood Orange",
    uniform_seed: 111.2,
    uniform_palette_colors_hex: ["#1A0A00", "#4A1500", "#CC3300", "#FF6633", "#FF9966"],
    uniform_motion_speed: 0.7,
    uniform_flow_rotation_radians: 0.5,
    uniform_warp_strength: 0.8,
    uniform_warp_scale: 1.9,
    uniform_turbulence: 0.5,
    uniform_brightness: 1.08,
    uniform_contrast: 1.28,
    uniform_saturation: 1.2,
    uniform_grain_amount: 0.14,
    uniform_grain_size: 1.3,
    uniform_reduce_motion_enabled: 0,
    quality_resolution_scale: 0.75,
    quality_fps_cap: 60,
  },
];
